# Generated by Django 5.1.15 on 2026-06-15 18:48

import apps.orders.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        default=apps.orders.models.generate_order_number,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending payment"),
                            ("paid", "Paid"),
                            ("routing", "Routing"),
                            ("partially_fulfilled", "Partially fulfilled"),
                            ("fulfilled", "Fulfilled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("payer_email", models.EmailField(blank=True, max_length=254)),
                ("payer_name", models.CharField(blank=True, max_length=255)),
                ("base_currency", models.CharField(max_length=3)),
                ("currency", models.CharField(max_length=3)),
                (
                    "fx_rate_locked",
                    models.DecimalField(decimal_places=10, default=1, max_digits=20),
                ),
                ("subtotal_base", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("discount_base", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total_base", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "subtotal_charged",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_charged",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_charged", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("ship_name", models.CharField(blank=True, max_length=255)),
                ("ship_line1", models.CharField(blank=True, max_length=255)),
                ("ship_line2", models.CharField(blank=True, max_length=255)),
                ("ship_city", models.CharField(blank=True, max_length=120)),
                ("ship_region", models.CharField(blank=True, max_length=120)),
                ("ship_postal_code", models.CharField(blank=True, max_length=32)),
                ("ship_country", models.CharField(blank=True, max_length=2)),
                ("ship_phone", models.CharField(blank=True, max_length=32)),
                ("coupon_codes", models.JSONField(blank=True, default=list)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True, unique=True
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sku", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price_base", models.DecimalField(decimal_places=2, max_digits=12)),
                ("line_total_base", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_price_charged", models.DecimalField(decimal_places=2, max_digits=12)),
                ("line_total_charged", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fulfillment_type", models.CharField(max_length=20)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="orders.order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="catalog.variant",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
