# Generated by Django 5.1.15 on 2026-06-18 21:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderInquiry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("call", "Call"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("cart", "Cart"),
                            ("checkout", "Checkout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("customer_phone", models.CharField(blank=True, max_length=40)),
                ("note", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("delivered_to_ops", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "order inquiries",
                "ordering": ("-created_at",),
            },
        ),
    ]
