# Generated by Django 5.1.15 on 2026-06-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderinquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending payment"),
                    ("paid", "Paid"),
                    ("routing", "Processing"),
                    ("partially_fulfilled", "Partially fulfilled"),
                    ("fulfilled", "Fulfilled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="pending",
                max_length=24,
            ),
        ),
    ]
