# Generated by Django 5.1.15 on 2026-06-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
