# Generated by Django 5.1.15 on 2026-06-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_telegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="notify_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="notify_telegram",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_bot_token",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
