# Generated by Django 5.1.15 on 2026-06-15 18:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_key", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("ordered", "Ordered"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=12,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "share_token",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True, unique=True
                    ),
                ),
                ("share_created_at", models.DateTimeField(blank=True, null=True)),
                ("share_expires_at", models.DateTimeField(blank=True, null=True)),
                ("share_revoked", models.BooleanField(default=False)),
                ("allow_payer_to_set_shipping", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CartLine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("added_unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
