# Generated by Django 5.1.15 on 2026-06-15 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("catalog", "0001_initial"),
        ("promotions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupons",
            field=models.ManyToManyField(blank=True, related_name="carts", to="promotions.coupon"),
        ),
        migrations.AddField(
            model_name="cart",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cartline",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="cart.cart"
            ),
        ),
        migrations.AddField(
            model_name="cartline",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_lines",
                to="catalog.variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartline",
            constraint=models.UniqueConstraint(
                fields=("cart", "variant"), name="uniq_cartline_variant"
            ),
        ),
    ]
