# Generated by Django 5.1.15 on 2026-06-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="shipping",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
