# Generated by Django 5.1.15 on 2026-06-15 17:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217, e.g. USD.",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("symbol", models.CharField(default="$", max_length=8)),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                (
                    "rounding_increment",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=12),
                ),
                (
                    "charm_pricing",
                    models.BooleanField(
                        default=False,
                        help_text="After rounding, end prices in .99 (e.g. 20 → 19.99).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "currencies",
                "ordering": ("position", "code"),
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base", models.CharField(db_index=True, max_length=3)),
                ("quote", models.CharField(db_index=True, max_length=3)),
                ("rate", models.DecimalField(decimal_places=10, max_digits=20)),
                ("source", models.CharField(default="mock", max_length=40)),
                ("fetched_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "ordering": ("-fetched_at",),
                "indexes": [
                    models.Index(
                        fields=["base", "quote", "-fetched_at"], name="currency_ex_base_1ac7b5_idx"
                    )
                ],
            },
        ),
    ]
