# Generated by Django 5.1.15 on 2026-06-15 18:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed", "Fixed amount")],
                        max_length=12,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "min_spend",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                ("first_order_only", models.BooleanField(default=False)),
                ("stackable", models.BooleanField(default=True)),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("used_count", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, the discount applies only to items in this category.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupons",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ("code",),
            },
        ),
    ]
