# Generated by Django 5.1.15 on 2026-06-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="authorization_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
