# Generated by Django 5.1.15 on 2026-06-15 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "adapter",
                    models.CharField(
                        default="mock", help_text="Adapter key, e.g. 'mock'.", max_length=40
                    ),
                ),
                ("api_base_url", models.URLField(blank=True)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("sync_cadence_minutes", models.PositiveIntegerField(default=60)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SupplierStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(db_index=True, max_length=64)),
                ("available", models.PositiveIntegerField(default=0)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("supplier", "sku"), name="uniq_supplier_stock")
                ],
            },
        ),
    ]
