# Generated by Django 5.1.15 on 2026-06-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="markup_percent",
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
        ),
    ]
