# Generated by Django 5.1.15 on 2026-06-15 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable actor snapshot (e.g. email) preserved even if the user is deleted.",
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        help_text="Logical resource type, e.g. 'storeconfig.Setting'.",
                        max_length=120,
                    ),
                ),
                ("target_id", models.CharField(blank=True, max_length=120)),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, help_text="{'field': {'before': x, 'after': y}}"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log entry",
                "verbose_name_plural": "audit log",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"], name="common_audi_target__65ba7e_idx"
                    ),
                    models.Index(fields=["action"], name="common_audi_action_288430_idx"),
                ],
            },
        ),
    ]
