# Generated by Django 5.1.15 on 2026-06-20 18:13

from django.db import migrations, models
from django.db.models import F


def backfill_full_stock(apps, schema_editor):
    """Seed the stock-bar baseline from current on-hand for existing stock."""
    StockItem = apps.get_model("inventory", "StockItem")
    StockItem.objects.update(full_stock=F("on_hand"))


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="full_stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_full_stock, migrations.RunPython.noop),
    ]
