# Generated by Django 5.1.15 on 2026-06-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_supplier_variant_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
