# Generated by Django 5.1.15 on 2026-06-20 16:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_discount_percent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="features",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="rating_avg",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=3),
        ),
        migrations.AddField(
            model_name="product",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="variant",
            name="moq",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="variant",
            name="price_tiers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("author_name", models.CharField(blank=True, max_length=120)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=160)),
                ("body", models.TextField(blank=True)),
                ("is_verified_purchase", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("published", "Published"), ("hidden", "Hidden")],
                        db_index=True,
                        default="published",
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("product", "user"),
                        name="uniq_review_per_user_product",
                    )
                ],
            },
        ),
    ]
