# Generated by Django 5.1.15 on 2026-06-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_features_product_rating_avg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_flash_sale",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
