# Generated by Django 5.1.15 on 2026-06-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_is_flash_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_public_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
