name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: prime
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/nasuru-api"

      - name: Run remote commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: prime
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/nasuru-api
            export PATH="$HOME/.local/bin:$PATH"
            uv sync --no-dev
            uv run python manage.py migrate --noinput
            uv run python manage.py collectstatic --noinput
            sudo systemctl daemon-reload
            sudo systemctl restart gunicorn celery-worker celery-beat

